app.security.admin-google-ids=${APP_SECURITY_ADMIN_GOOGLE_IDS:}

spring.datasource.url=${PROD_DB_SOURCE:}
spring.datasource.username=${PROD_DB_USER:}
spring.datasource.password=${PROD_DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration